//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Mensagens {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Mensagens() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Common.Mensagens", typeof(Mensagens).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Produto incluido com sucesso !!!.
        /// </summary>
        public static string ADICIONAR_PRODUTOS {
            get {
                return ResourceManager.GetString("ADICIONAR_PRODUTOS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O programa já está em execução, Aguarde ou verifique-se o mesmo não está minimizado na Barra de Tarefas.!.
        /// </summary>
        public static string AGUARDE_SISTEMA {
            get {
                return ResourceManager.GetString("AGUARDE_SISTEMA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O arquivo foi exportado com sucesso no caminho especificado: {0}..
        /// </summary>
        public static string ARQUIVO_EXPORTADO_COM_SUCESSO {
            get {
                return ResourceManager.GetString("ARQUIVO_EXPORTADO_COM_SUCESSO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O arquivo {0} não foi localizado !.
        /// </summary>
        public static string ARQUIVO_NAO_LOCALIZADO {
            get {
                return ResourceManager.GetString("ARQUIVO_NAO_LOCALIZADO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deseja editar o Produto selecionado: {0}?.
        /// </summary>
        public static string CONFIRMAR_EDITAR_PRODUTO {
            get {
                return ResourceManager.GetString("CONFIRMAR_EDITAR_PRODUTO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deseja apagar o produto selecionado: {0}?.
        /// </summary>
        public static string CONFIRMAR_EXCLUIR_PRODUTO {
            get {
                return ResourceManager.GetString("CONFIRMAR_EXCLUIR_PRODUTO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Atenção! Estes dados NÃO CORRESPONDEM ao seu usuário e senha de acesso ao Sistema Controle de Lotes. A alteração dos campos:[Nome do banco de dados],[Usuário SQL Server] e [Senha] devem ser realizadas, caso haja a necessidade de uma configuração de conexão diferente da padrão do sistema. Deseja realmente editar estes campos?.
        /// </summary>
        public static string EDITAR_CONFIGURACAO_PADRAO {
            get {
                return ResourceManager.GetString("EDITAR_CONFIGURACAO_PADRAO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Produto alterado com sucesso !!!.
        /// </summary>
        public static string EDITAR_PRODUTOS {
            get {
                return ResourceManager.GetString("EDITAR_PRODUTOS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Você deve selecionar um registro para ser alterado !.
        /// </summary>
        public static string ERRO_EDITAR_PRODUTO {
            get {
                return ResourceManager.GetString("ERRO_EDITAR_PRODUTO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Você deve selecionar um registro a ser excluído !.
        /// </summary>
        public static string ERRO_EXCLUIR_PRODUTO {
            get {
                return ResourceManager.GetString("ERRO_EXCLUIR_PRODUTO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Produto excluido com sucesso !!!.
        /// </summary>
        public static string EXCLUIR_PRODUTO {
            get {
                return ResourceManager.GetString("EXCLUIR_PRODUTO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arquivos de texto (*.txt)|*.txt|Todos os arquivos (*.*)|*.*.
        /// </summary>
        public static string FILTRO {
            get {
                return ResourceManager.GetString("FILTRO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO produtos (codbarra, descricao, preco) values (&apos;{0}&apos;, &apos;{1}&apos;, &apos;{2}&apos;).
        /// </summary>
        public static string INSERIR_LINHAS {
            get {
                return ResourceManager.GetString("INSERIR_LINHAS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selecionar Arquivo..
        /// </summary>
        public static string SELECIONAR_ARQUIVO {
            get {
                return ResourceManager.GetString("SELECIONAR_ARQUIVO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não possível conectar ao SQL Server com os dados informados. Por favor confira: Se o MSSQL Server está instalado em: &quot;localhost&quot; Se os demais dados: Nome do banco de dados(ECCINF), Usuário(sa) e Senha, estão corretos. Em caso de dificuldade entre em contato com nosso suporte.Detalhe do erro: {0};.
        /// </summary>
        public static string TESTE_CONEXAO {
            get {
                return ResourceManager.GetString("TESTE_CONEXAO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conexão Falhou.
        /// </summary>
        public static string TESTE_FALHOU {
            get {
                return ResourceManager.GetString("TESTE_FALHOU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conexão OK.
        /// </summary>
        public static string TESTE_OK {
            get {
                return ResourceManager.GetString("TESTE_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deus é Fiel.
        /// </summary>
        public static string VETOR_INICIALIZACAO {
            get {
                return ResourceManager.GetString("VETOR_INICIALIZACAO", resourceCulture);
            }
        }
    }
}
